name: 'Multiplatform docker build'
description: 'Build multiarch image and push to ecr'
inputs:
  lein-version:
    description: 'Version of leiningen to install'
    required: false
    default: '2.10.0'
runs:
  using: "composite"
  steps:
    - name: Install leiningen
      env:
        LEIN_VERSION: 2.10.0
        LEIN_INSTALL: /usr/local/bin/
        LEIN_ROOT: 1
      shell: bash
      run: |
        set -x; mkdir -p $LEIN_INSTALL \
        && wget -q https://github.com/technomancy/leiningen/archive/$LEIN_VERSION.tar.gz \
        && mkdir ./leiningen \
        && tar -xzf $LEIN_VERSION.tar.gz  -C ./leiningen/ --strip-components=1 \
        && mv leiningen/bin/lein-pkg $LEIN_INSTALL/lein \
        && rm -rf $LEIN_VERSION.tar.gz ./leiningen \
        && chmod 0755 $LEIN_INSTALL/lein \
        && wget -q https://github.com/technomancy/leiningen/releases/download/$LEIN_VERSION/leiningen-$LEIN_VERSION-standalone.zip \
        && wget -q https://github.com/technomancy/leiningen/releases/download/$LEIN_VERSION/leiningen-$LEIN_VERSION-standalone.zip.asc \
        && rm -f leiningen-$LEIN_VERSION-standalone.zip.asc \
        && mkdir -p /usr/share/java \
        && mv leiningen-$LEIN_VERSION-standalone.zip /usr/share/java/leiningen-$LEIN_VERSION-standalone.jar
